ITERATIONS: int 
RUNS: int 
STATIONS: int
MAX_LOCAL_IMPROVEMENTS: int = 20

#Simulated Annealing
SA_COOLING_RATE = 0.9
SA_ITERATIONS_PER_TEMPERATURE = 10
SA_MIN_TEMPERATURE = 0.01
SA_TARGET_ACCEPTANCE = 0.7
SA_TEMPERATURE_SAMPLES = 20
SA_RANDOM_SEED = 42
SA_MAX_NO_IMPROVEMENT_STAGES = 3
