ITERATIONS: int 
RUNS: int 
STATIONS: int
MAX_LOCAL_IMPROVEMENTS: int = 20
EJECT_K: int = 3

#Simulated Annealing
SA_COOLING_RATE = 0.97                                
SA_ITERATIONS_PER_TEMPERATURE = 100
SA_MIN_TEMPERATURE = 1.0
SA_TARGET_ACCEPTANCE = 0.6
SA_TEMPERATURE_SAMPLES = 100
SA_RANDOM_SEED = 42
SA_MAX_NO_IMPROVEMENT_STAGES = 100

# Task 3: Enhanced SA
SA_REANNEALING_ROUNDS = 2
SA_REANNEALING_TEMP_FRACTION = 0.5
SA_MIN_ITERATIONS_PER_STAGE = 30
SA_MAX_ITERATIONS_PER_STAGE = 100
SA_INTENSIFICATION_INTERVAL = 5
SA_ACCEPTANCE_HIGH = 0.7
SA_ACCEPTANCE_LOW = 0.3
SA_ALPHA_FAST = 0.85
SA_ALPHA_SLOW = 0.95
SA_MAX_TIME: float = 60.0

# VNS
VNS_K_MAX: int = 4
VNS_SHAKING_TRIALS: int = 10
VNS_MAX_NO_IMPROVE: int = 20
VNS_MAX_TIME: float = 60.0
VNS_RANDOM_SEED: int = 42
